### ISSUE TITLE
Using deprecated DiscordAPI object

### ISSUE THREAD

**Issue by rauenzi** [danegottwald/BetterDiscordPlugins#1]
The `DiscordAPI` from ZLib is deprecated as of over a year ago <https://rauenzi.github.io/BDPluginLibrary/docs/module-DiscordAPI.html>

While I will still accept your plugin into the repo, I highly suggested updating this. If you need help on how feel free to reach out either here or on Discord.

**Comment by danegottwald** [comment]
I went ahead and fixed the issue in 71c2819. Thanks for pointing that out.
