### ISSUE TITLE
Unable to hide preview.

### ISSUE THREAD

**Issue by thefaurie** [danegottwald/BetterDiscordPlugins#4]
In the description it says that it will automatically hide the stream after 3 streams are up, does that include my stream? I am unable to find the setting to hide my preview.

**Comment by danegottwald** [comment]
Yes, that does include your own stream.  So once you and two others are streaming, your stream preview will become hidden.  You can disable that and always hide your stream by disabling the setting by clicking the gear icon under the plugin in the Better Discord Plugin setting.  There is no need to manually enable or disable the stream preview, it is done automatically when either condition is met.

**Comment by thefaurie** [comment]
Hmm, its not hiding my stream with two others and I cannot see the the gear icon where you described it. It is displaying as 'ZeresPluginLibrary'. Is this normal?

**Comment by danegottwald** [comment]
Try deleting the plugin from the plugin directory in FIle Explorer and adding it again.  It should be in the list alongside ZeresPluginLibrary.

**Comment by thefaurie** [comment]
That worked out, thank you!
